# Generated by Django 5.2.6 on 2025-09-03 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='api',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='data_residency',
            field=models.CharField(default='any', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='deployment',
            field=models.CharField(default='either', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='eu_residency',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='hipaa',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='integrations',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='vendor',
            name='performance',
            field=models.IntegerField(default=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='price',
            field=models.FloatField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='security',
            field=models.IntegerField(default=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='soc2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='sso',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vendor',
            name='support',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vendor',
            name='team_size_supported',
            field=models.IntegerField(default=0),
        ),
    ]
