# Generated by Django 5.2.6 on 2025-09-03 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_vendor_api_vendor_data_residency_vendor_deployment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vendor',
            old_name='eu_residency',
            new_name='has_sso',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='sso',
            new_name='iso27001',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='performance',
            new_name='perf_latency_ms',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='price',
            new_name='perf_uptime_pct',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='score',
            new_name='price_monthly',
        ),
        migrations.RenameField(
            model_name='vendor',
            old_name='deployment',
            new_name='support_tier',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='category',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='description',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='security',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='support',
        ),
        migrations.RemoveField(
            model_name='vendor',
            name='team_size_supported',
        ),
        migrations.AddField(
            model_name='vendor',
            name='deployment_options',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='data_residency',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
